# Fly.io configuration for Telegram Domain Checker Bot
app = "telegram-domain-checker"
primary_region = "sin"  # Singapore region for better performance in Asia

[build]

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.restart]]
  policy = "always"

[metrics]
  port = 9091
  path = "/metrics"